### PR TITLE
use getProjectDir instead of getRootDir

### LINKED ISSUE #108: Plugin fails when using deep project structure
I have a project that has layout like this:

```
 - root
   | - ios
   | - android
   | - handler (in google cloud)
   | - trigger (in google cloud)
   | - etc..
```
When I run `./gradlew handler:appengineStage` from the root directory, staging fails with exception 
> Directory '[removed]/root/src/main/appengine' specified for property 'stagingConfig.appEngineDirectory' does not exist.

With plugin version 1.0 this used to work, but not anymore with 1.1. Should I have one appengine directory in the root folder and then separate appengine folders in handler and trigger folders?

All the projects are deployed to the same Google Cloud project, but represent different Services, so the cron.yaml should go to root/src/main/appengine, but the app.yaml files to project specific appengine folders? Is this correct? I have src/main/appengine folder in all projects that are destined to be deployed to Google Cloud, but not in the root project.

### PR DESCRIPTION
**Pull request by loosebazooka**
fixes #108

### CODE REVIEW

File: src/main/java/com/google/cloud/tools/gradle/appengine/flexible/extension/StageFlexible.java [hunk 1]
```diff
@@ -42,7 +42,7 @@
 
   public StageFlexible(Project project, File stagingDirectory) {
     this.project = project;
-    File projectRoot = project.getRootDir();
+    File projectRoot = project.getProjectDir();
```
Comment (akerekes) [inline src/main/java/com/google/cloud/tools/gradle/appengine/flexible/extension/StageFlexible.java]: could be called `projectDir` or `projectDirectory` instead

Comment (loosebazooka) [inline src/main/java/com/google/cloud/tools/gradle/appengine/flexible/extension/StageFlexible.java]: True, that might be clearer. Lemme udpate
