### PR TITLE
Fix UP-TO-DATE annotations

### LINKED ISSUE #318: Warning on task property validation when building
What's this? Should this be taken care of?

```
$ ./gradlew clean build
...
>  Task :validateTaskProperties
Task property validation finished with warnings:
  - Warning: Task type 'com.google.cloud.tools.gradle.appengine.appyaml.StageAppYamlTask': property 'stagingExtension.extraFilesDirectories' is not annotated with an input or output annotation.
  - Warning: Task type 'com.google.cloud.tools.gradle.appengine.standard.StageStandardTask': property 'stageStandardExtension.dockerfile' has @Input annotation used on property of type java.io.File.
```

### PR DESCRIPTION
**Pull request by loosebazooka**
Fixes #318.

- Input -> InputFiles on dockerFile for appengine-web.xml staging.
- InputFiles on extraFilesDirectory method renamed to an actual
  getter.
- Also renames the configuration generater to actual name.

### CODE REVIEW

File: src/test/java/com/google/cloud/tools/gradle/appengine/appyaml/StageAppYamlExtensionTest.java [hunk 1]
```diff
@@ -101,11 +103,12 @@ public void testToStageArchiveConfiguration_emptyExtraFiles() {
...
 
-    AppYamlProjectStageConfiguration generatedConfig = extension.toStageArchiveConfiguration();
+    AppYamlProjectStageConfiguration generatedConfig = extension.toAppYamlProjectStageConfiguration();
     Assert.assertEquals(appEngineDirectory.toPath(), generatedConfig.getAppEngineDirectory());
     Assert.assertEquals(stagingDirectory.toPath(), generatedConfig.getStagingDirectory());
     Assert.assertEquals(artifact.toPath(), generatedConfig.getArtifact());
     Assert.assertEquals(dockerDirectory.toPath(), generatedConfig.getDockerDirectory());
     Assert.assertEquals(0, generatedConfig.getExtraFilesDirectory().size());
   }
+
```
Comment (TadCordle) [inline src/test/java/com/google/cloud/tools/gradle/appengine/appyaml/StageAppYamlExtensionTest.java]: Intentional newline?

Comment (loosebazooka) [reply src/test/java/com/google/cloud/tools/gradle/appengine/appyaml/StageAppYamlExtensionTest.java]: probs not, I think its from where I was trying to write an uptodate check test.

File: src/test/java/com/google/cloud/tools/gradle/appengine/TestProject.java [hunk 2]
```diff
@@ -77,6 +77,14 @@ public TestProject addAppYamlBuildFileWithHome() throws IOException {
     return this;
   }
 
+  /** Add a appyaml based appengine-gradle-plugin build file that specifies sdk home and version. */
+  public TestProject addAppYamlBuildFileWithExtraFilesDirectories() throws IOException {
+    addBuildFile("projects/AppEnginePluginTest/build-appyaml-extraFilesDirectories.gradle");
+    Files.createDirectories(
```
Comment (TadCordle) [inline src/test/java/com/google/cloud/tools/gradle/appengine/TestProject.java]: Not too familiar with how `TestProject` handles things, but should this use a temporary directory instead of just creating a normal directory?

File: src/test/java/com/google/cloud/tools/gradle/appengine/appyaml/StageAppYamlExtensionTest.java [hunk 3]
```diff
@@ -16,15 +16,23 @@
 
 package com.google.cloud.tools.gradle.appengine.appyaml;
 
+import static org.gradle.testkit.runner.TaskOutcome.SUCCESS;
```
Comment (TadCordle) [inline src/test/java/com/google/cloud/tools/gradle/appengine/appyaml/StageAppYamlExtensionTest.java]: Should we be using static imports?

File: src/test/java/com/google/cloud/tools/gradle/appengine/TestProject.java (hunk 2 above)
Comment (loosebazooka) [reply src/test/java/com/google/cloud/tools/gradle/appengine/TestProject.java]: Yeah it does use a temporary directory. The `TestProject` class itself is indifferent to it, but projectRoot is always set to a temp directory.

File: src/test/java/com/google/cloud/tools/gradle/appengine/appyaml/StageAppYamlExtensionTest.java (hunk 3 above)
Comment (loosebazooka) [reply src/test/java/com/google/cloud/tools/gradle/appengine/appyaml/StageAppYamlExtensionTest.java]: I'll fix this.
