### PR TITLE
Fix path for appengine-web.xml for standard/flex detection fallback

### LINKED ISSUE #136: Fix fallback mechanism for appengine standard detection
The default location should be `src/main/webapp/WEB-INF`, not `src/main/java/webapp/WEB-INF`

https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/master/src/main/java/com/google/cloud/tools/gradle/appengine/AppEnginePlugin.java#L57

### PR DESCRIPTION
**Pull request by loosebazooka**
fixes #136

### CODE REVIEW

File: src/main/java/com/google/cloud/tools/gradle/appengine/AppEnginePlugin.java [hunk 1]
```diff
@@ -54,7 +54,7 @@ private boolean isAppEngineStandard(Project project) {
     }
     // convention based lookup of appengine-web.xml as a fallback
     Path appengineWebXml =
-        project.getProjectDir().toPath().resolve("src/main/java/webapp/WEB-INF/appengine-web.xml");
+        project.getProjectDir().toPath().resolve("src/main/webapp/WEB-INF/appengine-web.xml");
```
Comment (patflynn) [inline src/main/java/com/google/cloud/tools/gradle/appengine/AppEnginePlugin.java]: Can we use the war plugin to get the webapp directory?

Comment (loosebazooka) [inline src/main/java/com/google/cloud/tools/gradle/appengine/AppEnginePlugin.java]: Yeah we do that, see [line 48](https://github.com/GoogleCloudPlatform/app-gradle-plugin/pull/139/files/5e7ebc6d2d2b781aaa877404222f0f5c4865310a#diff-e63a80ab373530959c0f994705e2a85cR48), this just covers the case that the war plugin is applied *after* the appengine plugin.
